#!/usr/bin/env python3
import logging
import sys
import traceback

from src.my_socket import MySocket
from src.arg_parser import parse_args
from src.game import Game

# Define default port constants
DEFAULT_PORT = 27993
TLS_PORT = 27994


if __name__ == '__main__':
    hostname, port, username, is_ssl = parse_args(sys.argv[1:])
    sock = MySocket()
    try:
        sock.connect(host=hostname, port=port, use_tls=is_ssl)
        game = Game(sock, username, log_level=logging.WARN)
        game.start_game()
    except Exception as e:
        traceback.print_exc()
